"""Research Export — generate structured MD and HTML from research briefs.

Exports research topics with their briefs and peer reviews into
clean Markdown and print-friendly HTML documents.
"""

from __future__ import annotations

import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


EXPORT_DIR = "data/exports"


def _log(msg: str) -> None:
    print(msg, file=sys.stderr, flush=True)


def _slugify(text: str, max_len: int = 40) -> str:
    """Convert text to a filename-safe slug."""
    slug = re.sub(r"[^\w\s-]", "", text.lower())
    slug = re.sub(r"[\s_]+", "-", slug).strip("-")
    return slug[:max_len]


def _fmt_timestamp(ts: float) -> str:
    """Format a unix timestamp as a readable date."""
    if not ts or ts <= 0:
        return "—"
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def get_export_content_markdown(
    topic: dict,
    brief: dict,
    reviews: list[dict] | None = None,
) -> str:
    """Return structured Markdown content as a string.

    Args:
        topic: Topic dict (from ResearchTopic.to_dict()).
        brief: Brief dict (from ResearchBrief.to_dict()).
        reviews: Optional list of review dicts.

    Returns:
        Markdown content string.
    """
    tags = ", ".join(topic.get("tags", [])) or "—"
    created = _fmt_timestamp(brief.get("created_at", 0))
    published = _fmt_timestamp(brief.get("published_at", 0))

    lines = [
        f"# {topic['title']}",
        "",
        f"**Status**: {topic.get('status', '?')} | **Priority**: {topic.get('priority', 'normal')}  ",
        f"**Author**: {brief.get('author_agent', '?')} | **Version**: v{brief.get('version', 1)}  ",
        f"**Created**: {created} | **Published**: {published}  ",
        f"**Tags**: {tags}",
        "",
        "---",
        "",
    ]

    # Summary
    summary = brief.get("summary", "").strip()
    if summary:
        lines += ["## Summary", "", summary, ""]

    # Main content
    content = brief.get("content", "").strip()
    if content:
        lines += ["## Research Brief", "", content, ""]

    # Key findings
    findings = brief.get("key_findings", [])
    if findings:
        lines += ["## Key Findings", ""]
        for i, f in enumerate(findings, 1):
            lines.append(f"{i}. {f}")
        lines.append("")

    # Sources
    sources = brief.get("sources", [])
    if sources:
        lines += ["## Sources", ""]
        for i, s in enumerate(sources, 1):
            lines.append(f"{i}. {s}")
        lines.append("")

    # Peer reviews
    if reviews:
        lines += ["## Peer Reviews", ""]
        for rev in reviews:
            reviewer = rev.get("reviewer_agent", "unknown")
            verdict = rev.get("verdict", "?")
            confidence = rev.get("confidence", 3)
            comments = rev.get("comments", "").strip()

            verdict_label = {
                "approve": "Approved",
                "request_changes": "Changes Requested",
                "reject": "Rejected",
            }.get(verdict, verdict)

            lines += [
                f"### Review by {reviewer} — {verdict_label}",
                f"**Confidence**: {confidence}/5",
                "",
            ]
            if comments:
                lines += [comments, ""]

            additions = rev.get("suggested_additions", [])
            if additions:
                lines.append("**Suggested additions:**")
                for a in additions:
                    lines.append(f"- {a}")
                lines.append("")

            corrections = rev.get("corrections", [])
            if corrections:
                lines.append("**Corrections:**")
                for c in corrections:
                    lines.append(f"- {c}")
                lines.append("")

            lines.append("---")
            lines.append("")

    lines += ["", "*Generated by PinkyBot Research Pipeline*", ""]
    return "\n".join(lines)


def export_brief_markdown(
    topic: dict,
    brief: dict,
    reviews: list[dict] | None = None,
) -> str:
    """Generate a structured Markdown file from a research brief.

    Returns:
        Path to the generated .md file.
    """
    os.makedirs(EXPORT_DIR, exist_ok=True)

    content = get_export_content_markdown(topic, brief, reviews)
    slug = _slugify(topic.get("title", "untitled"))
    ts = int(time.time())
    filename = f"{topic['id']}_{slug}_{ts}.md"
    path = os.path.join(EXPORT_DIR, filename)

    with open(path, "w") as f:
        f.write(content)

    _log(f"research-export: wrote MD to {path}")
    return path


def _markdown_to_html(md_content: str) -> str:
    """Convert markdown to HTML. Uses the markdown library if available, otherwise basic conversion."""
    try:
        import markdown
        return markdown.markdown(md_content, extensions=["tables", "fenced_code"])
    except ImportError:
        pass

    # Basic fallback: handle headers, bold, italic, lists, hr, paragraphs
    html_lines = []
    in_list = False

    for line in md_content.split("\n"):
        stripped = line.strip()

        if not stripped:
            if in_list:
                html_lines.append("</ol>")
                in_list = False
            html_lines.append("")
            continue

        # Horizontal rule
        if stripped == "---":
            html_lines.append("<hr>")
            continue

        # Headers
        if stripped.startswith("### "):
            html_lines.append(f"<h3>{_inline_md(stripped[4:])}</h3>")
            continue
        if stripped.startswith("## "):
            html_lines.append(f"<h2>{_inline_md(stripped[3:])}</h2>")
            continue
        if stripped.startswith("# "):
            html_lines.append(f"<h1>{_inline_md(stripped[2:])}</h1>")
            continue

        # Ordered list
        m = re.match(r"^(\d+)\.\s+(.+)", stripped)
        if m:
            if not in_list:
                html_lines.append("<ol>")
                in_list = True
            html_lines.append(f"<li>{_inline_md(m.group(2))}</li>")
            continue

        # Unordered list
        if stripped.startswith("- "):
            html_lines.append(f"<ul><li>{_inline_md(stripped[2:])}</li></ul>")
            continue

        # Paragraph
        html_lines.append(f"<p>{_inline_md(stripped)}</p>")

    if in_list:
        html_lines.append("</ol>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Convert inline markdown (bold, italic, code) to HTML."""
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    # Inline code
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    return text


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    color: #1a1a1a;
    background: #fff;
    line-height: 1.7;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 24px;
  }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; color: #111; }}
  h2 {{ font-size: 1.3rem; margin: 2rem 0 0.8rem; color: #222; border-bottom: 1px solid #e0e0e0; padding-bottom: 0.3rem; }}
  h3 {{ font-size: 1.1rem; margin: 1.5rem 0 0.5rem; color: #333; }}
  p {{ margin: 0.6rem 0; }}
  strong {{ color: #111; }}
  code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; font-family: "SF Mono", Monaco, "Cascadia Code", monospace; }}
  hr {{ border: none; border-top: 1px solid #ddd; margin: 1.5rem 0; }}
  ol, ul {{ padding-left: 1.5rem; margin: 0.5rem 0; }}
  li {{ margin: 0.3rem 0; }}
  a {{ color: #0066cc; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .meta {{ color: #666; font-size: 0.9rem; line-height: 2; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; color: #999; font-size: 0.85rem; font-style: italic; }}
  @media print {{
    body {{ padding: 0; max-width: none; font-size: 11pt; }}
    h1 {{ font-size: 18pt; }}
    h2 {{ font-size: 14pt; page-break-after: avoid; }}
    h3 {{ font-size: 12pt; page-break-after: avoid; }}
    hr {{ margin: 1rem 0; }}
    .no-print {{ display: none; }}
  }}
</style>
</head>
<body>
{body}
</body>
</html>
"""


def export_brief_html(
    topic: dict,
    brief: dict,
    reviews: list[dict] | None = None,
) -> str:
    """Generate a styled HTML document (print-friendly, suitable for Save as PDF).

    Returns:
        Path to the generated .html file.
    """
    os.makedirs(EXPORT_DIR, exist_ok=True)

    md_content = get_export_content_markdown(topic, brief, reviews)
    html_body = _markdown_to_html(md_content)
    title = topic.get("title", "Research Brief")

    html = _HTML_TEMPLATE.format(title=title, body=html_body)

    slug = _slugify(topic.get("title", "untitled"))
    ts = int(time.time())
    filename = f"{topic['id']}_{slug}_{ts}.html"
    path = os.path.join(EXPORT_DIR, filename)

    with open(path, "w") as f:
        f.write(html)

    _log(f"research-export: wrote HTML to {path}")
    return path


def export_brief_pdf(
    topic: dict,
    brief: dict,
    reviews: list[dict] | None = None,
) -> str:
    """Generate a PDF document from a research brief using WeasyPrint.

    Returns:
        Path to the generated .pdf file.
    """
    os.makedirs(EXPORT_DIR, exist_ok=True)

    md_content = get_export_content_markdown(topic, brief, reviews)
    html_body = _markdown_to_html(md_content)
    title = topic.get("title", "Research Brief")
    html = _HTML_TEMPLATE.format(title=title, body=html_body)

    slug = _slugify(topic.get("title", "untitled"))
    ts = int(time.time())
    filename = f"{topic['id']}_{slug}_{ts}.pdf"
    path = os.path.join(EXPORT_DIR, filename)

    from weasyprint import HTML
    HTML(string=html).write_pdf(path)

    _log(f"research-export: wrote PDF to {path}")
    return path
